# Generated by Django 2.0.2 on 2018-03-07 14:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_picture', models.ImageField(upload_to='df_goods')),
                ('goods_comment', models.CharField(max_length=100)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods_count', models.ImageField(upload_to='')),
                ('goods_unity', models.CharField(default='500g', max_length=20)),
                ('goods_tips', tinymce.models.HTMLField()),
                ('goods_click', models.ImageField(upload_to='')),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo'),
        ),
    ]
