# Generated by Django 2.0.2 on 2018-03-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_click',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_count',
            field=models.IntegerField(),
        ),
    ]
