# Generated by Django 2.0.2 on 2018-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=40)),
                ('user_email', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=20)),
                ('receiver_address', models.CharField(max_length=100)),
                ('receiver_post', models.CharField(max_length=10)),
                ('receiver_phone', models.CharField(max_length=11)),
            ],
        ),
    ]
