# Generated by Django 2.0.2 on 2018-03-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailinfo',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=6),
            preserve_default=False,
        ),
    ]
